### ISSUE TITLE
Blank error screen after logging in

### ISSUE THREAD

**Issue by burhanuday** [davquar/halfdot#30]
After logging in to my umami instance, i just see a blank error screen. 
Downloaded the latest version from fdroid

**Comment by burhanuday** [comment]
![Screenshot_20230409_234638.png](https://user-images.githubusercontent.com/25934701/230789785-404466c3-0e53-41fd-8d89-8d2cab653c1e.png)

**Comment by davquar** [comment]
Hello, what is the Umami instance version?

**Comment by burhanuday** [comment]
v1.38.0

**Comment by davquar** [comment]
I did a test on your Umami version and the problem is that in version 1.39 Umami did some [breaking API changes](https://github.com/umami-software/website/pull/89/files). Since HalfDot targets only the most recent API, older instances may not work anymore; in this case, v1.38 isn't compatible.

At the moment you can solve it by upgrading your Umami instance.

In the future it would be nice if HalfDot had backward compatibility. It *may* be time-consuming/hard to maintain, because Umami doesn't version their API, so some manual mapping needs to be done.
