### ISSUE TITLE
v2 wasn't released in f-droid due to build failure

### ISSUE THREAD

**Issue by ni554n** [davquar/halfdot#34]
https://gitlab.com/fdroid/fdroiddata/-/pipelines/852855936

**Comment by davquar** [comment]
Thank you!

The build job failed due to an error while building another app in the same batch as HalfDot.

There is already another pipeline that has been triggered, and I'm also seeing quite a lot of activity that look like a set of manual fixes to various apps metadata.

So maybe in the next hours/tomorrow the situation will be fixed; if not, I'll open an issue on fdroiddata.
